weak_cq_path:
cq_path:

model_setup:
  model_name: ""
  max_length: 400

hardware:
  gpus: '3'
  cpu_limit: 16
  distributed_backend: #'dp' # None

train_setup:
  do_train: true
  batch_size: 4
  accumulate_grad_batches: 4
  max_epochs: 1
  limit_train_batches: 1.0

  val_check_interval: 1.0
  warmup_steps: 5

  learning_rate: 3e-4
  adam_epsilon: 10e-8

hydra:
  run:
    dir: /nas/home/qasemi/CQplus/Outputs/${hydra.job.name}