weak_cq_path:
cq_path:

data_stats:
  counts: [8161,0,48451]
#  counts: [1,1,1]

model_setup:
  model_name: ""
  tuned_model_path:
  max_length: 64

hardware:
  gpus: '3'
  cpu_limit: 16
#  distributed_backend: #'dp' # None

train_setup:
  do_train: false
  batch_size: 4
  accumulate_grad_batches: 4
  max_epochs: 1
  limit_train_batches: 1.0

  val_check_interval: 0.1
  warmup_steps: 5

  learning_rate: 1e-05
  adam_epsilon: 1e-06

  weight_decay: 0.1
  beta1: 0.9
  beta2: 0.998

data_module:
  train_batch_size: 2 #4
  val_batch_size: 8

  pad_to_max_length: false
  preprocessing_num_workers: 4
  overwrite_cache: false

  dataloader_num_workers: 1 #4


hydra:
  run:
    dir: /nas/home/qasemi/CQplus/Outputs/${hydra.job.name}