process_method: processs_dataset

dataset_name: omcs

ascent_path: "~/CQplus/Outputs/Corpora/ASCENT/data/kb-05-02-2021.jsonl"
omcs_path: "~/CQplus/Outputs/Corpora/OMCS/omcs-sentences-more.txt"
#output_name: "matches.json"

ascent_method: process_all_sentences_snorkel

output_name: snorkel_matches.csv
output_examples: output_examples.csv

output_names:
  extract_all_sentences_df: 'all_sentences_df.csv'
  process_all_sentences_snorkel: 'snorkel_matches.csv'
  output_examples: 'output_examples.csv'
  labeling_matrix: 'LabelingMatrix.npy'

process_all_sentences:
  do_srl: false


predicate: 'used'
snorkel_epochs: 300
json_chunck_size: 1000



filtered_output_path: filtered_dataset.csv


filtered_omcs_path: "~/CQplus/Outputs/${hydra.job.name}/omcs/filtered_dataset.csv"
filtered_ascent_path: "~/CQplus/Outputs/${hydra.job.name}/ascent/filtered_dataset.csv"

merged_output_path: "~/CQplus/Outputs/${hydra.job.name}/merged_datasets.csv"


hydra:
  run:
    dir: "~/CQplus/Outputs/${hydra.job.name}/${dataset_name}"