dataset_name: "omcs, ascent"

ascent_path: "~/CQplus/Outputs/Corpora/ASCENT/data/kb-05-02-2021.jsonl"
omcs_path: "~/CQplus/Outputs/Corpora/OMCS/omcs-sentences-more.txt"

lf_recall_threshold: 0.0

output_names:
  extract_all_sentences_df: 'all_sentences_df.csv'
  ascent_sentences_df: 'ascent_sentences_df.csv'
  omcs_sentences_df: 'omcs_sentences_df.csv'
  process_all_sentences_snorkel: 'snorkel_matches.csv'
  output_examples: 'output_examples.csv'
  labeling_matrix: 'LabelingMatrix.npy'
  snorkel_output: "snorkel_matches.csv"
  snorkel_examples: "snorkel_output_examples.csv"

  filtered_output_path: "filtered_dataset.csv"

process_all_sentences:
  do_srl: false


snorkel_epochs: 300

username: 

hydra:
  run:
    dir: "/nas/home/${username}/CQplus/Outputs/${hydra.job.name}"