dataset_name: ascent

ascent_path: "~/CQplus/Outputs/Corpora/ASCENT/data/kb-05-02-2021.jsonl"
omcs_path: "~/CQplus/Outputs/Corpora/OMCS/omcs-sentences-more.txt"
#output_name: "matches.json"

ascent_method: process_all_sentences_snorkel

output_name: snorkel_matches.csv
output_examples: output_examples.csv

output_names:
  extract_all_sentences_df: 'all_sentences_df.csv'
  process_all_sentences_snorkel: 'snorkel_matches.csv'
  output_examples: 'output_examples.csv'
  labeling_matrix: 'LabelingMatrix.npy'

process_all_sentences:
  do_srl: false


predicate: 'used'
snorkel_epochs: 300
json_chunck_size: 1000

hydra:
  run:
    dir: "~/CQplus/Outputs/${hydra.job.name}/${dataset_name}"