ascent_path: "/nas/home/qasemi/CQplus/Outputs/Corpora/ASCENT/data/kb-05-02-2021.jsonl"
#output_name: "matches.json"
method:

output_names:
  extract_all_sentences: 'all_sentences.json'
  process_all_sentences: 'matched_sentences.json'
  extract_usedfor_sentences: 'usedfor_sentences.csv'
  extract_usedfor_assertions: 'usedfor_assertions.csv'

process_all_sentences:
  do_srl: false


predicate: 'used'

json_chunck_size: 1000

hydra:
  run:
    dir: /nas/home/qasemi/CQplus/Outputs/${hydra.job.name}