ascent_path: "/nas/home/pkhanna/CQplus/Outputs/Corpora/ASCENT/data/kb-05-02-2021.jsonl"
#output_name: "matches.json"
method: 'process_all_sentences_snorkel'

output_names:
  extract_all_sentences_df: 'all_sentences_df.csv'
  process_all_sentences_snorkel: 'snorkel_processed.csv'
  output_examples: 'output_examples.csv'

process_all_sentences:
  do_srl: false


predicate: 'used'
snorkel_epochs: 300
json_chunck_size: 1000

hydra:
  run:
    dir: /nas/home/pkhanna/CQplus/Outputs/${hydra.job.name}