corpus_path: /nas/home/pkhanna/omcs/omcs-sentences-more.txt
output_name: snorkel_matches.csv
output_examples: output_examples.csv
snorkel_epochs: 200


hydra:
  run:
    dir: /nas/home/pkhanna/CQplus/Outputs/snorkel_${hydra.job.name}
