util_method: filter

matches_path1: /nas/home/pkhanna/CQplus/Outputs/omcs_process_dataset_using_snorkel/snorkel_matches.csv
matches_path2: /nas/home/pkhanna/CQplus/Outputs/ascent_process_dataset_using_snorkel/snorkel_matches.csv

merged_dataset: /nas/home/pkhanna/CQplus/Outputs/merge_matches/final_merged.csv 

merged_output_path: final_merged.csv
filtered_output_path: filtered_dataset.csv


hydra:
  run:
    dir: "~/CQplus/Outputs/${hydra.job.name}/${util_method}"